import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { registerProjectTools } from "./tools/projects";
import { registerResearchTools } from "./research/tools";

export function createStudioMcpServer(origin: string) {
  const server = new McpServer({ name: "content-studio", version: "0.1.0" }, {
    instructions: "For new slides, select a template using only list_template_guides metadata. Do not read full project JSON or previews to compare candidates. Creation requires clone_project with a registered templateProjectId; no templates means creation is unavailable. After selection, read the cloned project before editing. Preserve inherited hook/body styles and account badges while replacing content. Template registration references the original project: editing it changes the template. set_reuse_guide updates project metadata; register_template and unregister_template manage designation only when requested by the user. Select by visual information structure and page flow, regardless of the current subject. Registration and cloning require a non-empty composition description. Registration can save composition atomically. Never auto-register to bypass creation restrictions or modify the original to fit a new post. Registration does not save active drafts. Find and select local images with your filesystem tools, then use set_local_image inside edit_project. Edit batches are one undo step. Fonts: oswald for hooks (700, Bold), space-grotesk for body headings (300-700, recommended 700), inter for body text (100-900, recommended 400-500), sans-serif for the Geist fallback (100-900). Text style fontStyle accepts normal or italic; Inter and Geist load true italics, Oswald and Space Grotesk use a synthesized slant. Projects are open tabs. Creation/clone/open adds a tab without switching the browser. Closed tabs reject edits; explicitly open and read again. Edit/undo require expectedTabId and expectedRevision from the latest read. Never write the app database directly. Research tools are optional and independent of project creation. Follow AGENTS.md research criteria or the user request, inspect criteriaEvaluation, and never treat unavailable reaction metrics as zero or qualifying. Collect post metadata and images only; do not fetch comment text. Reuse the same collection session when handling a confirmed CAPTCHA and close it when finished.",
  });
  registerProjectTools(server, origin);
  registerResearchTools(server);
  return server;
}
